name: bluebillywig
description: A new Flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  custom_lint: ^0.6.2
  flutter_test:
    sdk: flutter
  riverpod_lint: ^2.3.9
  very_good_analysis: ^5.1.0

flutter:
  plugin:
    platforms:
      android:
        package: com.bluebillywig.player
        pluginClass: BluebillywigPlugin
      ios:
        pluginClass: BluebillywigPlugin
